from typing import *
from eschool.mark import Mark


class EschoolUserInterface:
    def state(self) -> None: ...

    def get_marks(self) -> List[Mark]: ...

    def get_new_msgs(self) -> List[dict]: ...

    def read_msg(self, msg_id: str) -> None: ...

    def get_user_info(self) -> dict: ...

    def get_school_clazz(self) -> Tuple[str, str]: ...

    def get_username(self) -> str: ...

    def get_password(self) -> str: ...

    def get_cookies(self) -> Dict[str, str]: ...


class EschoolServerInterface:
    def login(self, username: str, password: str) -> Tuple[str, str]: ...

    def get_state(self, cookies: dict) -> dict: ...

    def get_marks(self, user_id: str, cookies: dict) -> List[Mark]: ...

    def get_new_msgs(self, cookies: dict, prs_id: str) -> List[dict]: ...

    def send_msg(self, msg: dict, cookies: dict, firebase_id: str) -> None: ...

    def get_school_clazz(self, prs_id: str, cookies: dict) -> tuple: ...

    def read_msg(self, msg_id: str, cookies: dict) -> None: ...
